# Generated by Django 3.2.7 on 2022-03-06 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_score_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='game',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='score', to='games.game'),
        ),
    ]
