# Generated by Django 3.2.7 on 2022-03-04 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nrtp',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
