# Generated by Django 3.2.7 on 2022-03-04 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0001_initial'),
        ('players_profile', '0002_profile_nrtp'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='leagues',
            field=models.ManyToManyField(null=True, related_name='players', to='leagues.League'),
        ),
    ]
