# Generated by Django 3.2.7 on 2022-03-04 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0001_initial'),
        ('players_profile', '0003_profile_leagues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='leagues',
            field=models.ManyToManyField(related_name='players', to='leagues.League'),
        ),
    ]
