# Generated by Django 3.2.7 on 2022-03-05 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players_profile', '0004_alter_profile_leagues'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='leagues',
        ),
    ]
