# Generated by Django 3.2.7 on 2022-03-04 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('description', models.TextField()),
                ('max_number_of_players', models.PositiveSmallIntegerField(default=20)),
                ('min_number_of_players', models.PositiveSmallIntegerField(default=4)),
                ('status', models.CharField(choices=[('OPEN', 'open'), ('IN-PROGRESS', 'in-progress'), ('ENDED', 'ended')], default='OPEN', max_length=20)),
            ],
        ),
    ]
